apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-files
data:
{{- range $filename, $content := .Values.configFiles }}
  {{ $filename }}: |
{{ tpl $content $ | indent 4 }}
{{- end }}
