apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
{{- with .Values.config }}
  RAILS_HOST_WITH_PORT: {{ .host }}
  CANVAS_LMS_ACCOUNT_NAME: {{ .setup.accountName }}
  CANVAS_LMS_STATS_COLLECTION: {{ .setup.statsCollection }}
{{- end }}
