apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-brandablecss
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.config.storage.brandableCss }}
  storageClassName: standard
