apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-files
spec:
  {{- with .Values.config.storage.files }}
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .request }}
  storageClassName: {{ .className }}
  {{- end }}
