apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
type: Opaque
stringData:
  {{- with .Values.config }}
  {{- with .security }}
  ENCRYPTION_KEY: {{ .encryptionKey | quote }}
  {{- end }}
  {{- with .setup }}
  CANVAS_LMS_ADMIN_EMAIL: {{ .admin.email }}
  CANVAS_LMS_ADMIN_PASSWORD: {{ .admin.password }}
  {{- end }}
  {{- with .database }}
  DATABASE_PASSWORD: {{ .password | quote }}
  {{- end }}
  {{- end }}
