{{- if .Values.rce.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: '{{ printf "%s-rce" (include "chart.fullname" .) }}'
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: rce
spec:
  type: {{ .Values.rce.service.type | default .Values.service.type }}
  ports:
    - port: {{ .Values.rce.port }}
      nodePort: {{ (.Values.rce.service.nodePort) }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: '{{ printf "%s-rce" (include "chart.name" .) }}'
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
